### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by azzamsa** [DavidMStraub/gramps-webapp#19]
This is not the core feature indeed, but do you consider to add multiple users feature ?

My only consideration is that the family data contains sensitive information, so: 1) I can log each user activity. Or 2) we can add ability (as an admin) to select what item should be presented in family tree graph. I vote for number two.

In many occasion I'll be hide the birth info, etc. and only shows their names. For privacy concern.

**Comment by DavidMStraub** [comment]
Indeed, this is something I was considering. I'm not 100% sure how much of the user management should be part of the app (frontend) though. Perhaps it's enough to allow specifying a SQLite database with credentials and providing a command line tool to add/remove/change users, at least as a first step.

Concerning user activity, one thing to consider is that currently, authentication is stateless via tokens, i.e. there is no "logged in" or "logged out" state on the server side. Once a user has a valid token, they can fetch the database and then browse the database as long as they want (until they close the browser window). The only calls to the API after that are for fetching note contents and images.

**Comment by azzamsa** [comment]
> Perhaps it's enough to allow specifying a SQLite database with credentials and providing a command line tool to add/remove/change users, at least as a first step.

Yeah, at least I can give access/revoke to specific people in my family.

> Concerning user activity ...

This is what I'm thinking right now. I'm super concern about everyone privacy in my family. So I need to ask them are they they okay the the published items, or not.

What's your opinion about privacy? any better approach?
maybe the default is to hide some info (such as birth info), since it's prone to scam.

**Comment by DavidMStraub** [comment]
I agree that privacy is crucial. This is also why I wanted to have some form of password protection from the beginning. Of course at some point we also want to share (part of) our research, but most people's Gramps DB does contain plenty of sensitive information. Publishing data about living people is illegal in the EU anyway (GDPR).

Since this app uses Gramps as backend, I think there are three ways to protect the data:
- hide living people
- hide private records
- password protection/user system.

At the moment, the first two options are implemented as global options; when adding a user system it would of course make sense to make this a per-user setting.

Concerning hiding living people, it should be stressed though that this is of limited use as implemented in Gramps: it does hide all information on living people, but the events and media are still visible - they are just not attached to a person anymore. So in general, I think using Gramps's private records and hiding them in the app (possibly on a per-user basis in the future) is the best way to go.

**Comment by azzamsa** [comment]
> At the moment, the first two options are implemented as global options; when adding a user system it would of course make sense to make this a per-user setting.

Agree.

> using Gramps's private records and hiding them in the app (possibly on a per-user basis in the future) is the best way to go.

agree. cool.

**Comment by DavidMStraub** [comment]
Since the basic multi-user functionality has been implemented in the master branch, I'll go ahead and close this issue while opening new, more specific ones like #28.

**Comment by azzamsa** [comment]
Yes, I always followed your commit and wiki edits. But haven't try them locally with my grampsdb, still have some other task at hand :)

Thanks for implementing this! thanks.
